### ISSUE TITLE
query of BSDS500 ods/ois/ap value

### ISSUE THREAD

**Issue by k3chencoco** [PXinTao/XYW-Net#6]
hi，
I used the codes of XYW-Net and the matlab code downloaded from the link. I add one line code to save the mat file in test.py.
But the matlab results show ODS=0.782 OIS=0.799 AP=0.810 R50=0.904, lower than the thesis mentioned 0.812 /0.827 /0.873.
I only used BSDS500 traning dataset. How to improve the values ODS/OIS/AP?

**Comment by PXinTao** [comment]
> hi， I used the codes of XYW-Net and the matlab code downloaded from the link. I add one line code to save the mat file in test.py. But the matlab results show ODS=0.782 OIS=0.799 AP=0.810 R50=0.904, lower than the thesis mentioned 0.812 /0.827 /0.873. I only used BSDS500 traning dataset. How to improve the values ODS/OIS/AP?

In our paper, we describe the use of the BSDS500 and PASCAL VOC datasets to augment the training dataset, which is a common practice. To help you better understand, I suggest you review the section in our paper that discusses the dataset augmentation in more detail.
“The BSDS500 dataset is commonly used for evaluating the perfor
mance of edge detection models. It consists of 200 training images, 100 
validation images, and 200 test images. In this paper, we follow the 
approach of (Cao, et al., 2020; Deng, et al., 2018; Xie & Tu, 2017) and 
augment the data by incorporating the PASCAL VOC dataset, thereby 
expanding the training data. ”

**Comment by k3chencoco** [comment]
thanks for your rapid response. have you trained the dataset only use BSDS500? Is it normal that the ODS/OIS/AP is lower only with BSDS500 than with BSDS500+PASCAL VOC?

**Comment by PXinTao** [comment]
> BSDS500 than with BSDS500+PASCAL VOC?

I don't have the results for only BSDS500. BSDS500 lower BSDS500+PASCAL VOC is a common phenomenon.

**Comment by k3chencoco** [comment]
Thanks! 
the last question: do you use the method as the website https://xavysp.github.io/MBIPED/ mentioned to augument the data od PASCAL VOC? [DexiNed](https://arxiv.org/pdf/1909.01955.pdf)

**Comment by PXinTao** [comment]
> Thanks! the last question: do you use the method as the website https://xavysp.github.io/MBIPED/ mentioned to augument the data od PASCAL VOC? [DexiNed](https://arxiv.org/pdf/1909.01955.pdf)

It is recommended to use data enhancement, which is why voc is added.

**Comment by k3chencoco** [comment]
thanks for you patient reply. this issue can be closed.
